source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'capybara'
gem 'cpf_faker'
gem 'cucumber'
gem 'faker'
gem 'rspec'
gem 'rufo'
gem 'selenium-webdriver'
gem 'httparty'
gem 'site_prism'
gem 'webdrivers'
gem 'roo'
gem 'rubocop'